### ISSUE TITLE
Fetch whole-brain parcellation instead of separated hemispheres for Julich-Brain

### ISSUE THREAD

**Issue by dickscheid** [ymzayek/EBRAINS-Connectivity-Analysis#1]

**Comment by dickscheid** [comment]
siibra provides a function `fetch_all` which should be used for that.

**Comment by ymzayek** [comment]
@dickscheid with `fetch_all` I get a 4D volume with overlapping label values. Nilearn maskers cannot handle that. I did a workaround to extract the timeseries separately and then combine for computing the connectivity matrix but I don't like this solution. I think in any case we can leave this for now since we talked about using the pmaps instead.

**Comment by dickscheid** [comment]
You are right, you should use fetch_relabelled() to get a 3D volume with gapless label indices. Like this:

```python
import siibra
julichbrain = siibra.parcellations.JULICH_BRAIN_CYTOARCHITECTONIC_MAPS_2_9
julich_maxprobmap = julichbrain.get_map(
    space=siibra.spaces.MNI152_2009C_NONL_ASYM, 
    maptype=siibra.MapType.LABELLED
)
labelled_volume, regionnames = julich_maxprobmap.fetch_relabelled()
```

`labelled_volume` is a 3D NIfTI as expected. `regionnames` will be a dict mapping the relabelled indices to region names. You can use the parcellation object to decode region names into region objects later on:

```python
julichbrain.decode_region(regionnames[10])
```

**Comment by ymzayek** [comment]
This worked just fine thanks!
